name: Generate HTML and SVG

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your default branch if different
    paths:
      - 'data.json'          # Trigger when data.json changes
      - 'app/**'             # Trigger when files in the app directory change
      - 'package.json'       # Trigger when package.json changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0
        with:
          persist-credentials: false  # Don't use the token from the checkout action

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '18'  # Use Node.js version 18

      - name: Install dependencies
        working-directory: app
        run: npm install

      - name: Generate HTML and SVG
        working-directory: app
        run: npm run generate

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: 'Auto-generated index.html and image.svg from data.json'
          file_pattern: |
            index.html
            image.svg